//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestMagazineEntities : DbContext
    {

        private static TestMagazineEntities _context;

        public TestMagazineEntities()
            : base("name=TestMagazineEntities")
        {
        }

        public static TestMagazineEntities GetContext()
        {
            if (_context == null)
                _context = new TestMagazineEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientSale> ClientSale { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
